SELECT TOP (1000) [Year]
      ,[Team]
      ,[NAME]
      ,[No]
      ,[Pos]
      ,[Ht]
      ,[Wt]
      ,[Age]
      ,[Exp]
      ,[College]
      ,[FirstName]
      ,[LastName]
      ,[Ft]
      ,[In]
      ,[Inches]
      ,[NumGrp]
      ,[column17]
      ,[column18]
      ,[Num]
      ,[NumGrp2]
      ,[Players]
  FROM [Sales].[dbo].[FPD]
